name: Feature Request
description: Request a new feature be added to UKMM.
title: "[Feature request]: "
labels: ["enhancement", "triage"]
assignees:
  - GingerAvalanche
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: what-feature
    attributes:
      label: Feature Explanation
      description: What would you like to see UKMM do?
      placeholder: Please be as detailed as possible.
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Reason for this Feature
      description: What problem will this feature solve?
      placeholder: Please be as detailed as possible.
    validations:
      required: true
  - type: upload
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your feature.
    validations:
      required: false
