use std::{
    ffi::OsString,
    io::{stdin, stdout, Write},
    option::Option,
    path::{Path, PathBuf},
};

use anyhow_ext::{Context, Result};
use smartstring::alias::String;
use uk_manager::{core, mods::LookupMod, settings::Platform};
use uk_mod::{unpack::ModReader, Manifest, Meta, ModOptionGroup, OptionGroup};

use crate::gui::{package, tasks};

xflags::xflags! {
    src "./src/cli.rs"

    /// Command line interface for U-King Mod Manager
    cmd ukmm {
        /// Verbose logging for debugging
        optional -d, --debug
        /// Run using settings in same folder as executable
        optional -p, --portable
        /// Automatically deploy after running command (redunant with `deploy` command)
        optional -D, --deploy
        /// Install a mod
        cmd install {
            /// Path to the mod to install
            required path: PathBuf
            /// The profile to install the mod in
            optional profile: String
            /// Use default options for mods with configuration
            optional --default-options
            /// Comma-separated list of option names to enable
            optional --options options_list: OsString
        }
        /// Package a mod
        cmd package {
            /// Path to the mod root directory
            required path: PathBuf
            /// Path to the output mod archive
            required output: PathBuf
            /// Path to the meta file for the mod
            required meta: PathBuf
        }
        /// Uninstall a mod
        cmd uninstall {
            /// The index of the mod to uninstall
            optional index: usize
            /// The profile to uninstall the mod from
            optional profile: String
        }
        /// Refresh merge
        cmd remerge {}
        /// Deploy mods
        cmd deploy {}
        /// Change current mode (Switch or Wii U)
        cmd mode {
            /// Mode to activate (Switch or Wii U)
            required platform: Platform
        }
        /// Show info about a mod (including available options)
        cmd info {
            /// Path to the mod to inspect
            required path: PathBuf
        }
    }
}
// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Ukmm {
    pub debug: bool,
    pub portable: bool,
    pub deploy: bool,
    pub subcommand: UkmmCmd,
}

#[derive(Debug)]
pub enum UkmmCmd {
    Install(Install),
    Package(Package),
    Uninstall(Uninstall),
    Remerge(Remerge),
    Deploy(Deploy),
    Mode(Mode),
    Info(Info),
}

#[derive(Debug)]
pub struct Install {
    pub path: PathBuf,
    pub profile: Option<String>,

    pub default_options: bool,
    pub options: Option<OsString>,
}

#[derive(Debug)]
pub struct Package {
    pub path: PathBuf,
    pub output: PathBuf,
    pub meta: PathBuf,
}

#[derive(Debug)]
pub struct Uninstall {
    pub index: Option<usize>,
    pub profile: Option<String>,
}

#[derive(Debug)]
pub struct Remerge;

#[derive(Debug)]
pub struct Deploy;

#[derive(Debug)]
pub struct Mode {
    pub platform: Platform,
}

#[derive(Debug)]
pub struct Info {
    pub path: PathBuf,
}

impl Ukmm {
    #[allow(dead_code)]
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end

macro_rules! input {
    () => {{
        stdout().flush()?;
        let mut _input = std::string::String::new();
        stdin().read_line(&mut _input).unwrap();
        _input
    }};
}

#[derive(Debug)]
pub struct Runner {
    core: core::Manager,
    cli:  Ukmm,
}

impl Runner {
    pub fn new(cli: Ukmm) -> Self {
        Self {
            core: core::Manager::init().unwrap(),
            cli,
        }
    }

    fn check_mod(&self, path: &Path) -> Result<Option<(PathBuf, Meta)>> {
        let (mod_, path) = match ModReader::open(path, vec![]) {
            Ok(mod_) => (mod_, path.to_path_buf()),
            Err(e) => {
                match uk_manager::mods::convert_gfx(&self.core, path, None) {
                    Ok(path) => {
                        log::info!("Opening mod at {}", path.display());
                        (
                            ModReader::open(&path, vec![])
                                .context("Failed to open converted mod")?,
                            path,
                        )
                    }
                    Err(e2) => {
                        anyhow_ext::bail!(
                            "Could not open mod. Error when attempting to open as UKMM mod: {}. \
                             Error when attempting to open as legacy mod: {}.",
                            e,
                            e2
                        )
                    }
                }
            }
        };
        println!("Installing {}...", mod_.meta.name);
        Ok(Some((path, mod_.meta)))
    }

    fn resolve_options(
        meta: &Meta,
        default_options: bool,
        options_list: &Option<std::ffi::OsString>,
    ) -> Result<Vec<uk_mod::ModOption>> {
        if meta.options.is_empty() {
            return Ok(vec![]);
        }

        if !default_options && options_list.is_none() {
            anyhow_ext::bail!(
                "This mod contains configuration options. Use --default-options to select \
                 defaults, or --options \"Option1,Option2\" to select specific options.\n\
                 Run `ukmm info <path>` to see available options."
            );
        }

        let requested_names: Option<Vec<std::string::String>> =
            options_list.as_ref().map(|list| {
                list.to_string_lossy()
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .collect()
            });

        let mut selected = Vec::new();
        for group in &meta.options {
            match group {
                OptionGroup::Exclusive(g) => {
                    if let Some(ref names) = requested_names {
                        if let Some(opt) = g
                            .options
                            .iter()
                            .find(|o| names.iter().any(|n| n == o.name.as_str()))
                        {
                            selected.push(opt.clone());
                        } else if g.required {
                            if let Some(ref default_path) = g.default {
                                if let Some(opt) =
                                    g.options.iter().find(|o| &o.path == default_path)
                                {
                                    selected.push(opt.clone());
                                }
                            }
                        }
                    } else if default_options {
                        if let Some(ref default_path) = g.default {
                            if let Some(opt) =
                                g.options.iter().find(|o| &o.path == default_path)
                            {
                                selected.push(opt.clone());
                            }
                        }
                    }
                }
                OptionGroup::Multiple(g) => {
                    if let Some(ref names) = requested_names {
                        for opt in &g.options {
                            if names.iter().any(|n| n == opt.name.as_str()) {
                                selected.push(opt.clone());
                            }
                        }
                        // If none explicitly matched but defaults exist, fall back
                        if selected.is_empty() && default_options {
                            for opt in &g.options {
                                if g.defaults.contains(&opt.path) {
                                    selected.push(opt.clone());
                                }
                            }
                        }
                    } else if default_options {
                        for opt in &g.options {
                            if g.defaults.contains(&opt.path) {
                                selected.push(opt.clone());
                            }
                        }
                    }
                }
            }
        }

        if !selected.is_empty() {
            println!("Selected options:");
            for opt in &selected {
                println!("  - {}", opt.name);
            }
        }

        Ok(selected)
    }

    fn print_mod_info(path: &Path) -> Result<()> {
        let mod_ = match ModReader::open(path, vec![]) {
            Ok(m) => m,
            Err(_) => {
                let meta = Meta::parse(path.join("meta.yml"))
                    .or_else(|_| Meta::from_mod(path))
                    .context("Could not read mod metadata")?;
                println!("Name:        {}", meta.name);
                println!("Version:     {}", meta.version);
                println!("Author:      {}", meta.author);
                println!("Category:    {}", meta.category);
                println!("Description: {}", meta.description);
                if !meta.options.is_empty() {
                    Self::print_options(&meta);
                }
                return Ok(());
            }
        };
        println!("Name:        {}", mod_.meta.name);
        println!("Version:     {}", mod_.meta.version);
        println!("Author:      {}", mod_.meta.author);
        println!("Category:    {}", mod_.meta.category);
        println!("Description: {}", mod_.meta.description);
        if !mod_.meta.options.is_empty() {
            Self::print_options(&mod_.meta);
        } else {
            println!("\nThis mod has no configuration options.");
        }
        Ok(())
    }

    fn print_options(meta: &Meta) {
        println!("\nAvailable options:");
        for group in &meta.options {
            match group {
                OptionGroup::Exclusive(g) => {
                    println!(
                        "\n  [Exclusive] {} {}",
                        g.name(),
                        if g.required() { "(required)" } else { "" }
                    );
                    if !g.description().is_empty() {
                        println!("  {}", g.description());
                    }
                    for opt in g.options() {
                        let is_default = g
                            .default
                            .as_ref()
                            .map(|d| d == &opt.path)
                            .unwrap_or(false);
                        println!(
                            "    - {} {}",
                            opt.name,
                            if is_default { "(default)" } else { "" }
                        );
                        if !opt.description.is_empty() {
                            println!("      {}", opt.description);
                        }
                    }
                }
                OptionGroup::Multiple(g) => {
                    println!(
                        "\n  [Multiple] {} {}",
                        g.name(),
                        if g.required() { "(required)" } else { "" }
                    );
                    if !g.description().is_empty() {
                        println!("  {}", g.description());
                    }
                    for opt in g.options() {
                        let is_default = g.defaults.contains(&opt.path);
                        println!(
                            "    - {} {}",
                            opt.name,
                            if is_default { "(default)" } else { "" }
                        );
                        if !opt.description.is_empty() {
                            println!("      {}", opt.description);
                        }
                    }
                }
            }
        }
    }

    fn deploy(&self) -> Result<()> {
        let deployer = self.core.deploy_manager();
        if deployer.pending() {
            println!("Deploying changes...");
            deployer.deploy()?;
            println!("Deployment complete");
        } else {
            println!("No changes pending deployment");
        };
        Ok(())
    }

    pub fn run(self) -> Result<()> {
        if self.cli.debug {
            env_logger::init();
            log::set_max_level(log::LevelFilter::Debug);
        }
        match &self.cli.subcommand {
            UkmmCmd::Mode(Mode { platform }) => {
                self.core
                    .settings_mut()
                    .apply(|s| s.current_mode = *platform)?;
                self.core.reload()?;
                println!("Mode changed to {:?}", platform);
                if self.cli.deploy {
                    self.deploy()?;
                }
                println!("Done!");
            }
            UkmmCmd::Info(Info { path }) => {
                Self::print_mod_info(path)?;
            }
            UkmmCmd::Install(Install {
                path,
                profile,
                default_options,
                options,
            }) => {
                if let Some((path, meta)) = self.check_mod(path)? {
                    let selected_options =
                        Self::resolve_options(&meta, *default_options, options)?;
                    let mods = self.core.mod_manager();
                    let mod_ = mods.add(&path, profile.as_ref())?;
                    let hash = mod_.as_map_id();
                    mods.set_enabled(hash, true, profile.as_ref())?;
                    if !selected_options.is_empty() {
                        mods.set_enabled_options(hash, selected_options)?;
                    }
                    mods.save()?;
                    println!("Applying mod to load order...");
                    let deployer = self.core.deploy_manager();
                    let installed_mod = mods
                        .mods()
                        .find(|m| m.hash() == hash)
                        .context("Failed to find installed mod")?;
                    deployer.apply(Some(installed_mod.manifest()?.as_ref().clone()))?;
                    if self.cli.deploy {
                        self.deploy()?;
                    }
                    println!("Done!");
                }
            }
            UkmmCmd::Package(pkg) => {
                println!("Packaging mod...");
                let builder = package::ModPackerBuilder {
                    source: pkg.path.clone(),
                    dest:   pkg.output.clone(),
                    meta:   Meta::parse(&pkg.meta)?,
                };
                tasks::package_mod(&self.core, builder)?;
                println!("Done!");
            }
            UkmmCmd::Remerge(_) => {
                println!("Remerging...");
                tasks::apply_changes(&self.core, vec![], None)?;
                println!("Done!");
            }
            UkmmCmd::Uninstall(Uninstall { index, profile }) => {
                let mut manifests = Manifest::default();
                let mod_manager = self.core.mod_manager();
                let mods = mod_manager.mods().collect::<Vec<_>>();

                if let Some(index_value) = index {
                    let mod_ = mods
                        .get(*index_value)
                        .with_context(|| format!("Mod {} does not exist", index_value))?;
                    println!("Removing mod {}...", &mod_.meta.name);
                    mod_manager.del(mod_, profile.as_ref())?;
                    mod_manager.save()?;
                    manifests.extend(mod_.manifest()?.as_ref());
                } else {
                    println!("Installed mods:");
                    for (i, mod_) in mods.iter().enumerate() {
                        println!(
                            "{}. {} (v{}) by {}",
                            i + 1,
                            &mod_.meta.name,
                            &mod_.meta.version,
                            &mod_.meta.author
                        );
                    }
                    print!("Enter mod(s) to uninstall, separated by commas: ");
                    let mut manifests = Manifest::default();
                    for id in input!().replace(' ', "").split(',') {
                        let mod_ = mods
                            .get(id.trim().parse::<usize>().context("Invalid mod number")? - 1)
                            .with_context(|| format!("Mod {} does not exist", id))?;
                        println!("Removing mod {}...", &mod_.meta.name);
                        mod_manager.del(mod_, profile.as_ref())?;
                        mod_manager.save()?;
                        manifests.extend(mod_.manifest()?.as_ref());
                    }
                }

                println!("Applying changes to merge...");
                self.core.deploy_manager().apply(Some(manifests))?;
                if self.cli.deploy {
                    self.deploy()?;
                }
                println!("Done!");
            }
            UkmmCmd::Deploy(_) => self.deploy()?,
        };
        Ok(())
    }
}
