name: Rust

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-02-28
    - name: Crate cache
      uses: actions/cache@v3
      with:
        key: ubuntu-latest-cargo-cache
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ./target
    - name: Install GTK
      run: sudo apt update && sudo apt install libgtk-3-dev	
    - uses: LoliGothick/clippy-check@master
      name: Check clippy
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
